version: 2
jobs:
  build:
    working_directory: ~/gcs-database-history
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run:
          name: gcp_credentials
          command: |
            echo $GCP_CREDENTIALS | base64 --decode > gcp_credentials.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp_credentials.json"' >> $BASH_ENV
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/gcs-database-history-0.1.0-SNAPSHOT.jar
          destination: uberjar
