version: 2
jobs:
  build:
    working_directory: ~/gcs-database-history
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/cci-demo-clojure.jar
          destination: uberjar
